.\" Manpage for jdu
.TH man 8 "03 Oct 2021" "0.2" "jdu man page"
.SH NAME
jdu \- disk utilization in json format
.SH SYNOPSIS
jdu FOLDER1 [FOLDER2] ... [FOLDERN]
.SH DESCRIPTION
jdu is a simple clone of the /bin/du command, that prints the output in json format
.SH OPTIONS
The jdu does not take any options. However, you must supply one or more folder names
.SH SEE ALSO
du(8)
.SH BUGS
No known bugs.
.SH AUTHOR
Jose Vicente Nunez (kodegeek.com@protonmail.com)
