.\" Manpage for jutmp
.TH man 8 "03 Oct 2021" "0.2" "jutmp man page"
.SH NAME
jutmp \- output of last command in JSON format
.SH SYNOPSIS
jutmp
.SH DESCRIPTION
jutmp is a simple clone of the /usr/bin/last command, that prints the output in json format
.SH OPTIONS
The jutmp does not take any options or flags
.SH SEE ALSO
last(8)
.SH BUGS
No known bugs.
.SH AUTHOR
Jose Vicente Nunez (kodegeek.com@protonmail.com)
